# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Satus',
            new_name='Status',
        ),
    ]
