# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20170416_0542'),
        ('projects', '0002_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status')),
            ],
        ),
    ]
